stashing the ptp stuff for the future

diff --git a/src/main/deploy/timing/ptp4linit b/src/main/deploy/timing/ptp4linit
--- a/src/main/deploy/timing/ptp4linit
+++ b/src/main/deploy/timing/ptp4linit
@@ -1,29 +1,67 @@
 #!/bin/sh
-# /etc/init.d/ptp4linit
-
 ### BEGIN INIT INFO
 # Provides:          ptp4linit
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Starts ptp4l at boot
-# Description:       Enables Precision Time Protocol (PTP) using ptp4l.
+# Description:       ptp4l grandmaster clock
 ### END INIT INFO
+
+SCRIPT="/usr/bin/ptp4l -i eth0 -S -l 6"
+RUNAS=admin
+
+PIDFILE=/var/run/ptp4l.pid
+LOGFILE=/var/log/ptp4l.log
+
+start() {
+  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+  echo 'Service started' >&2
+}
+
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
+  fi
+  echo 'Stopping service…' >&2
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
+}
+
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+    update-rc.d -f <NAME> remove
+    rm -fv "$0"
+  fi
+}
 
 case "$1" in
   start)
-    echo "Starting ptp4l"
-    /home/lvuser/deploy/timing/ptp4l -i eth0 -S
+    start
     ;;
   stop)
-    echo "Stopping ptp4l"
-    # Add command to stop ptp4l if applicable
+    stop
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  restart)
+    stop
+    start
     ;;
   *)
-    echo "Usage: /etc/init.d/ptp4linit {start|stop}"
-    exit 1
-    ;;
+    echo "Usage: $0 {start|stop|restart|uninstall}"
 esac
-
-exit 0
